apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  namespace: basic-ns
  labels:
    app: basic-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-app
        image: thomassojan/fastapi-base-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests: 
            cpu: 500m
            memory: 300Mi
          limits: 
            memory: 400Mi
        volumeMounts:
          - name: basic-app-vol
            mountPath: /etc/config
      volumes:
        - name: basic-app-vol
          configMap: 
            name: basic-app-cm
