apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-app-ingress
  namespace: basic-ns
spec:
  rules:
  - host: basic-app.com
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend: 
          service:
            name: basic-app-svc
            port:
              number: 8080
