resources:
  - ../../application

namespace: kustomize-ns-prod

commonLabels:
  environment: prod

patches:
- path: replica_count.yaml
  target:
    kind: Deployment
- path: resource_limit.yaml
  target:
    kind: Deployment

configMapGenerator:
- name: basic-app-cm
  namespace: kustomize-ns
  behavior: replace
  files:
  - config/.env