apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
spec: 
  template:
    spec:
      containers:
      - name: basic-app
        resources:
          requests: 
            cpu: 80m
            memory: 128Mi
          limits: 
            cpu: 800m
            memory: 500Mi
       
