apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-app-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ThomasSojan/KubernetesAdventure.git
    targetRevision: main
    path: 2.ArgoCD/K8sComponents
  destination: 
    server: https://kubernetes.default.svc
    namespace: basic-ns

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
