apiVersion: v1
kind: Service
metadata:
  name: basic-app-svc
  namespace: kustomize-ns
spec:
  type: ClusterIP
  selector:
    app: basic-app
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
